### ISSUE TITLE
All text in h1

### ISSUE THREAD

**Issue by sirinoks** [juuuuuuun/jun-ssg#1]
When reading a file, instead of putting it in paragraphs, it puts the whole text in `<h1>` instead.

**Comment by juuuuuuun** [comment]
![updated code to fix(jun)](https://user-images.githubusercontent.com/45890241/133740818-afb02504-61f4-4e3f-aa24-d4be5cc339d7.png)
I updated and now all function is working as well.

**Comment by juuuuuuun** [comment]
![final fixed](https://user-images.githubusercontent.com/45890241/133862971-13e34155-086d-4697-8f86-86b5caa09062.png)
finally completely solved the problem 100% fully works now :)
