### ISSUE TITLE
No comments in code

### ISSUE THREAD

**Issue by sirinoks** [juuuuuuun/jun-ssg#3]
Like, absolutely 0. 
I do get what the code does, it seems understandable. Though it was unclear to me how getting data from json worked for example, or some other things like yargs. Maybe add a link to yargs documentation in comments?

**Comment by juuuuuuun** [comment]
![added comments](https://user-images.githubusercontent.com/45890241/133862809-c5ee3758-e348-4bdb-ab2f-9de9143f1ab7.png)
I added comments at each part of codes
